In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
### sentences
sentences = [
    'I love programming in Python',
    'Python is great for data science',
    'Deep learning is fascinating',
    'I enjoy solving problems with code',
    'Data analysis is crucial for insights'
]

In [4]:
sentences

['I love programming in Python',
 'Python is great for data science',
 'Deep learning is fascinating',
 'I enjoy solving problems with code',
 'Data analysis is crucial for insights']

In [5]:
## Define the vocabulary size
vocab_size = 1000 

In [6]:
## One Hot Representation
one_hot_words = [one_hot(words,vocab_size) for words in sentences]
one_hot_words

[[863, 33, 610, 115, 339],
 [339, 483, 133, 606, 648, 40],
 [723, 888, 483, 57],
 [863, 122, 183, 603, 604, 765],
 [648, 725, 483, 232, 606, 576]]

In [7]:
## word Embedding Representation
from tensorflow.keras.layers import Embedding
# from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sentences_length = 8
embedded_docs = pad_sequences(one_hot_words, maxlen=sentences_length, padding='pre', )
print(embedded_docs)

[[  0   0   0 863  33 610 115 339]
 [  0   0 339 483 133 606 648  40]
 [  0   0   0   0 723 888 483  57]
 [  0   0 863 122 183 603 604 765]
 [  0   0 648 725 483 232 606 576]]


In [11]:
## feature representation
model = Sequential()
model.add(Embedding(vocab_size, 10, input_length=sentences_length))
model.compile('adam', 'mse')

In [12]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 8, 10)             10000     
                                                                 
Total params: 10000 (39.06 KB)
Trainable params: 10000 (39.06 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [13]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 116ms/step


array([[[ 0.01492753, -0.02804688, -0.01631735, -0.00152755,
          0.02191058,  0.02135874, -0.03969435,  0.02813106,
          0.04405499, -0.04962444],
        [ 0.01492753, -0.02804688, -0.01631735, -0.00152755,
          0.02191058,  0.02135874, -0.03969435,  0.02813106,
          0.04405499, -0.04962444],
        [ 0.01492753, -0.02804688, -0.01631735, -0.00152755,
          0.02191058,  0.02135874, -0.03969435,  0.02813106,
          0.04405499, -0.04962444],
        [-0.01246452,  0.01602947,  0.00420624, -0.0348837 ,
         -0.02066759,  0.04304601,  0.0468874 ,  0.02187223,
          0.03136131,  0.03572235],
        [ 0.02099865, -0.00184009, -0.03517644,  0.0033012 ,
         -0.03085597, -0.01260142, -0.02696826, -0.02414671,
         -0.0012989 ,  0.01080515],
        [ 0.00504266, -0.02185707, -0.04601413,  0.04737652,
          0.03197373, -0.03066024, -0.02198073, -0.00712327,
          0.0188884 , -0.02736869],
        [-0.01230367, -0.01006451,  0.00658312, -0.0

In [14]:
embedded_docs[0]

array([  0,   0,   0, 863,  33, 610, 115, 339])

In [15]:
print(model.predict(embedded_docs[0]))

1/1 [==============================] - 0s 36ms/step
[[ 0.01492753 -0.02804688 -0.01631735 -0.00152755  0.02191058  0.02135874
  -0.03969435  0.02813106  0.04405499 -0.04962444]
 [ 0.01492753 -0.02804688 -0.01631735 -0.00152755  0.02191058  0.02135874
  -0.03969435  0.02813106  0.04405499 -0.04962444]
 [ 0.01492753 -0.02804688 -0.01631735 -0.00152755  0.02191058  0.02135874
  -0.03969435  0.02813106  0.04405499 -0.04962444]
 [-0.01246452  0.01602947  0.00420624 -0.0348837  -0.02066759  0.04304601
   0.0468874   0.02187223  0.03136131  0.03572235]
 [ 0.02099865 -0.00184009 -0.03517644  0.0033012  -0.03085597 -0.01260142
  -0.02696826 -0.02414671 -0.0012989   0.01080515]
 [ 0.00504266 -0.02185707 -0.04601413  0.04737652  0.03197373 -0.03066024
  -0.02198073 -0.00712327  0.0188884  -0.02736869]
 [-0.01230367 -0.01006451  0.00658312 -0.01694456 -0.00308143 -0.01071838
  -0.03386734  0.00081481 -0.02262053  0.02412653]
 [-0.03975072 -0.03390677 -0.03887466 -0.03288928  0.02223997 -0.01860464